(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("map_line",
{ "height":8,
 "infinite":false,
 "layers":[
        {
         "data":[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 115, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 115, 115, 115, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 115, 115, 115, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 115, 115, 115, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 115, 115, 115, 115, 115, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 115, 115, 115, 115, 115, 115, 115, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         "height":8,
         "id":1,
         "name":"Tile Layer 1",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":25,
         "x":0,
         "y":0
        }, 
        {
         "data":[10, 10, 10, 0, 0, 0, 0, 0, 0, 0, 9, 0, 116, 12, 121, 121, 121, 70, 126, 126, 126, 33, 34, 33, 34, 10, 10, 0, 9, 10, 10, 0, 116, 0, 11, 0, 0, 0, 0, 0, 12, 121, 78, 131, 126, 126, 41, 42, 41, 42, 0, 57, 49, 29, 0, 116, 116, 0, 11, 0, 32, 0, 0, 0, 99, 0, 75, 0, 14, 14, 0, 0, 54, 55, 24, 50, 51, 92, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 62, 63, 24, 0, 57, 57, 0, 116, 0, 11, 0, 71, 0, 0, 0, 0, 0, 32, 0, 75, 13, 39, 40, 13, 33, 34, 33, 34, 58, 59, 136, 9, 116, 116, 0, 11, 79, 0, 0, 0, 0, 0, 12, 131, 131, 13, 47, 48, 13, 41, 42, 41, 42, 0, 9, 0, 136, 0, 0, 0, 30, 30, 30, 0, 0, 21, 0, 0, 0, 131, 13, 13, 13, 13, 126, 126, 33, 34, 12, 12, 9, 0, 0, 0, 9, 0, 0, 0, 0, 21, 0, 0, 0, 0, 0, 121, 121, 121, 126, 126, 126, 41, 42],
         "height":8,
         "id":3,
         "name":"Tile Layer 2",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":25,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":2,
         "name":"Object Layer 1",
         "objects":[
                {
                 "gid":91,
                 "height":32,
                 "id":3,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":96,
                 "y":128
                }, 
                {
                 "gid":91,
                 "height":32,
                 "id":4,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":128,
                 "y":128
                }, 
                {
                 "gid":91,
                 "height":32,
                 "id":5,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":160,
                 "y":128
                }, 
                {
                 "gid":91,
                 "height":32,
                 "id":6,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":192,
                 "y":128
                }, 
                {
                 "gid":91,
                 "height":32,
                 "id":7,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":224,
                 "y":128
                }, 
                {
                 "gid":91,
                 "height":32,
                 "id":8,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":256,
                 "y":128
                }, 
                {
                 "gid":91,
                 "height":32,
                 "id":9,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":288,
                 "y":128
                }, 
                {
                 "gid":91,
                 "height":32,
                 "id":10,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":320,
                 "y":128
                }, 
                {
                 "gid":19,
                 "height":32,
                 "id":11,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":352,
                 "y":122
                }, 
                {
                 "gid":19,
                 "height":32,
                 "id":12,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":352,
                 "y":122
                }, 
                {
                 "gid":19,
                 "height":32,
                 "id":13,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":384,
                 "y":122
                }, 
                {
                 "gid":19,
                 "height":32,
                 "id":14,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":416,
                 "y":122
                }, 
                {
                 "gid":27,
                 "height":32,
                 "id":15,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":352,
                 "y":153
                }, 
                {
                 "gid":27,
                 "height":32,
                 "id":16,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":384,
                 "y":153
                }, 
                {
                 "gid":27,
                 "height":32,
                 "id":17,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":416,
                 "y":153
                }, 
                {
                 "gid":96,
                 "height":32,
                 "id":18,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":448,
                 "y":128
                }, 
                {
                 "gid":96,
                 "height":32,
                 "id":19,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":479,
                 "y":128
                }, 
                {
                 "gid":96,
                 "height":32,
                 "id":20,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":512,
                 "y":128
                }, 
                {
                 "gid":96,
                 "height":32,
                 "id":21,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":544,
                 "y":128
                }, 
                {
                 "gid":96,
                 "height":32,
                 "id":22,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":576,
                 "y":128
                }, 
                {
                 "gid":96,
                 "height":32,
                 "id":23,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":608,
                 "y":127
                }, 
                {
                 "gid":96,
                 "height":32,
                 "id":24,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":640,
                 "y":126
                }, 
                {
                 "gid":96,
                 "height":32,
                 "id":25,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":672,
                 "y":126
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":7,
 "nextobjectid":27,
 "orientation":"orthogonal",
 "renderorder":"left-down",
 "tiledversion":"1.2.5",
 "tileheight":32,
 "tilesets":[
        {
         "firstgid":1,
         "source":"..\/..\/..\/..\/\u8cc7\u6599\u753b\u50cf\/pipo-map001.tsx"
        }, 
        {
         "firstgid":89,
         "source":"..\/..\/..\/..\/\u8cc7\u6599\u753b\u50cf\/pipo-map001_at-sabaku.tsx"
        }, 
        {
         "firstgid":94,
         "source":"..\/..\/..\/..\/\u8cc7\u6599\u753b\u50cf\/pipo-map001_at-miti.tsx"
        }, 
        {
         "firstgid":99,
         "source":"..\/..\/..\/..\/\u8cc7\u6599\u753b\u50cf\/kabocha.tsx"
        }, 
        {
         "firstgid":111,
         "source":"..\/..\/..\/..\/\u8cc7\u6599\u753b\u50cf\/pipo-map001_at-umi.tsx"
        }, 
        {
         "firstgid":116,
         "source":"..\/..\/..\/..\/\u8cc7\u6599\u753b\u50cf\/pipo-map001_at-yama1.tsx"
        }, 
        {
         "firstgid":121,
         "source":"..\/..\/..\/..\/\u8cc7\u6599\u753b\u50cf\/pipo-map001_at-yama2.tsx"
        }, 
        {
         "firstgid":126,
         "source":"..\/..\/..\/..\/\u8cc7\u6599\u753b\u50cf\/pipo-map001_at-yama3.tsx"
        }, 
        {
         "firstgid":131,
         "source":"..\/..\/..\/..\/\u8cc7\u6599\u753b\u50cf\/pipo-map001_at-tuti.tsx"
        }, 
        {
         "firstgid":136,
         "source":"..\/..\/..\/..\/\u8cc7\u6599\u753b\u50cf\/pipo-map001_at-mori.tsx"
        }],
 "tilewidth":32,
 "type":"map",
 "version":1.2,
 "width":25
});